FO: correct submit of carrier form
PrestaShop/ps_legalcompliance pull request #40
Opened 2017-08-14 11:35 UTC by Shopmonauten

submitting the form via $(this) instead of $(#form)submits the button which results the form. The difference is now, that the processCarrier methods get executed because they rely on the name of the button (processCarrier...). This was not executed before.

2017-08-14 12:15 UTC, aleeks submitted a review, later dismissed
It makes sense to me, need to be tested.

2020-03-25 08:00 UTC, Progi1984 submitted a review, later dismissed

2020-03-25 14:09 UTC, PierreRambaud commented on views/js/fo_aeuc_tnc.js
> +			type: 'hidden',
Don't mix tab and spaces please, weird indent.

2020-03-25 14:09 UTC, PierreRambaud requested changes
See comment

2020-05-27 06:58 UTC, Progi1984 commented
Ping @Shoprunners

2020-05-27 07:11 UTC, Shoprunners commented
I corrected the spaces and tabs, hopefully to the right branch?

2020-05-27 07:16 UTC, Progi1984 commented
@Shoprunners I don't see the change actually. So it doesn't seem on the right branch.

2020-05-27 07:40 UTC, Shoprunners commented
> @Shoprunners I don't see the change actually. So it doesn't seem on the right branch.

I hope, i got the right one this time, sorry, not yet very used to the review and resubmit process

2020-05-27 08:06 UTC, Progi1984 commented
@Shoprunners No problem ;)

2020-05-27 08:06 UTC, Progi1984 submitted a review, later dismissed

2020-05-27 08:15 UTC, PierreRambaud submitted a review, later dismissed

2020-05-27 08:16 UTC, PierreRambaud approved these changes

2020-05-27 09:24 UTC, Progi1984 approved these changes

2020-05-28 08:43 UTC, sarahdib commented
Hello @Shoprunners 
Could you please provide us a test case scenario in order to test this pr ?

Thank you :)

2020-05-28 09:26 UTC, Shoprunners commented
Hi,
well, this bugfix is for i.e. this:

https://www.prestashop.com/forums/topic/626896-aeuc-module-and-actioncarrierprocess/

Hope this helps.

2020-06-10 08:17 UTC, sarahdib commented
Hello @Shoprunners 

We need a scenario not technical in order to test this pr.
Like : 
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

Thank you

2020-06-10 10:12 UTC, Shoprunners commented
Hi, 
you need a  module which hooks into official hook "actionCarrierProcess". When ps_legalcomplicance is installed, this hook will never execute.

It is going to be executed with this bugfix.

Should be a bugfix for this: https://github.com/PrestaShop/PrestaShop/issues/12780 as well.

2020-06-17 10:16 UTC, sarahdib commented
Hello @Shoprunners 
Could you provide us the module in order to test?

Thank you

2020-08-31 09:32 UTC, sarahdib commented
@Shoprunners 

We try to check the pr with a module and nothing change before and after the PR.

Could you give us a precise scenario in order to test ?

Thank you

2020-08-31 09:35 UTC, Shoprunners commented
Hi, I think, you can close this. Because the code in the core changed since 2017 and it is not reproducable in the latest versions.

2020-08-31 13:30 UTC, closed without merging